apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-error-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-user/sync-fail-demo.git
    targetRevision: HEAD
    path: bad/path/does-not-exist  # ❌ this will cause a sync error

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated: {}
