apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "echo 'Terminating...' && sleep 60"]
      initContainers:
      - name: init-demo
        image: busybox
        command: ['sh', '-c', 'echo "Sleeping..." && sleep 50 && echo "Done sleeping"']
        resources:
          requests:
            memory: "30Mi"
            cpu: "50m"
          limits:
            memory: "50Mi"
            cpu: "70m"
