apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: guestbook-ui
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - containerPort: 80
      - name: failing-container-1
        image: busybox:latest  
        command: ["/bin/sh", "-c", "echo 'Failing container 1'; exit 2"]
        resources:
          limits:
            memory: "64Mi"
      - name: failing-container-2
        image: busybox:latest  
        command: ["/bin/sh", "-c", "echo 'Failing container 2'; exit 3"]
        resources:
          limits:
            memory: "64Mi"
      - name: failing-container-3
        image: busybox:latest  
        command: ["/bin/sh", "-c", "echo 'Failing container 3'; exit 4"]
        resources:
          limits:
            memory: "64Mi"
