apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighbor-pod-deployment
  labels:
    app: neighbor-test  # Different app label from guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neighbor-test
  template:
    metadata:
      labels:
        app: neighbor-test
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - guestbook-ui  # Match your guestbook app label
            topologyKey: kubernetes.io/hostname  # Ensure same node placement
      containers:
      - name: neighbor-container
        image: nginx:latest  # Example image
        command: ["/bin/sh", "-c", "nginx & sleep 60 && nginx -s quit"]  # Run NGINX for 1 minute and terminate gracefully
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      initContainers:
      - name: init-container
        image: busybox
        command: ["sh", "-c", "sleep 60"]  # Init container sleeps for 60 seconds
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
